// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type PearlItem struct {
	ID        int64
	Itemid    int64
	Name      string
	Date      time.Time
	Sold      int64
	Preorders int64
}
