// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pearl_items.sql

package db

import (
	"context"
	"time"
)

const createPearlItem = `-- name: CreatePearlItem :exec
INSERT INTO pearl_items (
  itemid, name, date, sold, preorders
) 
SELECT $1, $2, $3, $4, $5
WHERE NOT EXISTS (SELECT 1 FROM pearl_items WHERE itemid = $1 AND date = $3)
`

type CreatePearlItemParams struct {
	Itemid    int64
	Name      string
	Date      time.Time
	Sold      int64
	Preorders int64
}

func (q *Queries) CreatePearlItem(ctx context.Context, arg CreatePearlItemParams) error {
	_, err := q.db.Exec(ctx, createPearlItem,
		arg.Itemid,
		arg.Name,
		arg.Date,
		arg.Sold,
		arg.Preorders,
	)
	return err
}

const deleteOldPearlItems = `-- name: DeleteOldPearlItems :exec
DELETE FROM pearl_items
WHERE date < now() - interval '3 weeks'
`

func (q *Queries) DeleteOldPearlItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldPearlItems)
	return err
}

const getPearlItems = `-- name: GetPearlItems :many
SELECT a.name,a.sold - b.sold AS sold,a.preorders FROM pearl_items a
INNER JOIN pearl_items b ON a.itemid = b.itemid
WHERE a.date = (SELECT MAX(date) FROM pearl_items)
AND b.date = (SELECT MAX(date) FROM pearl_items WHERE pearl_items.date <= $1)
ORDER BY a.name
`

type GetPearlItemsRow struct {
	Name      string
	Sold      int32
	Preorders int64
}

func (q *Queries) GetPearlItems(ctx context.Context, date time.Time) ([]GetPearlItemsRow, error) {
	rows, err := q.db.Query(ctx, getPearlItems, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPearlItemsRow
	for rows.Next() {
		var i GetPearlItemsRow
		if err := rows.Scan(&i.Name, &i.Sold, &i.Preorders); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
